services:
  db:
    image: mysql
    container_name: db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'backweb'
    ports:
      - '3306:3306'
  db2:
    image: mysql
    container_name: db2
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'backempresa'
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3305:3306'
  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "81:80"
  phpmyadmin2:
    image: phpmyadmin
    container_name: pma2
    links:
      - db2
    environment:
      PMA_HOST: db2
      PMA_PORT: 3306
    ports:
      - "82:80"

  eureka:
    image: javi9801/eurekabus:1.1
    container_name: eureka
    ports:
      - "8761:8761"

  busbalancer:
    image: javi9801/busbalancer:1.1
    container_name: busbalancer
    ports:
      - "8080:8080"
    links:
      - "eureka"
    depends_on:
      - eureka
    environment:
      eureka.client.service-url.defaultZone: http://eureka:8761/eureka

  backweb:
    image: javi9801/backweb:2
    container_name: backweb
    depends_on:
      - db
      - eureka
      - kafka1
      - busbalancer
    environment:
#      - spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
      - spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
      - spring.datasource.url=jdbc:mysql://db:3306/backweb
      - spring.datasource.password=root
      - spring.kafka.bootstrap-servers=kafka1:9092
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
      - message.group.name=groupId1
      - server.port=8081
      - spring.jpa.hibernate.ddl-auto=update
      - urlempresa=http://backempresa:8090/v0-empresa/token

    ports:
      - "8081:8081"

  backempresa:
    image: javi9801/backempresa:2
    container_name: backempresa
    depends_on:
      - db2
      - eureka
      - kafka1
      - busbalancer
    environment:
#      - spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
      - spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
      - spring.datasource.url=jdbc:mysql://db2:3306/backempresa
      - spring.kafka.bootstrap-servers=kafka1:9092
      - spring.datasource.password=root
      - server.port=8090
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
      - message.group.name=groupId2
      - spring.jpa.hibernate.ddl-auto=update
    ports:
      - "8090:8090"

  zookeeper1:
    image: wurstmeister/zookeeper
    container_name: zookeeper1
    ports:
      - "22181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
