server:
  port: 8080

eureka:
  client:
    fetch-registry : true
    register-with-eureka : true
  instance:
    hostname: localhost
spring:
  application:
    name : busBalancer
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: BackWeb
          uri: lb://BackWeb
          predicates:
            - Path=/v0/**
        - id: BackEmpresa
          uri: lb://BackEmpresa
          predicates:
            - Path=/v0-empresa/**